version: '3.8'

services:
  app:
    image: openjdk:11
    container_name: app1
    volumes:
      - ./ordrs-1.0-SNAPSHOT.jar:/app/ordrs.jar
    working_dir: /app
    entrypoint: ["java", "-jar", "ordrs.jar"]
    environment:
      - KAFKA_BROKER=host.docker.internal:29092  # Example: kafka-broker.mydomain.com:9092
      - KAFKA_TOPIC=orderss
      - TOTAL_RECORDS=100
      - BATCH_SIZE=5
      - FREQUENCY_MS=1000
      - DB_URL=jdbc:postgresql://ah-data-lab.duckdns.org:35432/moaz_db
      - DB_USER=moaz
      - DB_PASSWORD=moaz
      - CUSTOMERS_TABLE=customers
      - PRODUCTS_TABLE=productstess
      - ORDERS_TABLE=orders
